import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import sveltePlugin from 'esbuild-svelte'
import autoPreprocess from 'svelte-preprocess'
import fs from 'fs'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
const meta = process.argv[3] === 'meta'

esbuild
  .build({
    banner: {
      js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/closebrackets',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/comment',
      '@codemirror/fold',
      '@codemirror/gutter',
      '@codemirror/highlight',
      '@codemirror/history',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/matchbrackets',
      '@codemirror/panel',
      '@codemirror/rangeset',
      '@codemirror/rectangular-selection',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/stream-parser',
      '@codemirror/text',
      '@codemirror/tooltip',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      ...builtins,
    ],
    format: 'cjs',
    watch: !prod,
    target: 'es2016',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    metafile: meta,
    plugins: [
      sveltePlugin({
        preprocess: autoPreprocess(),
        compilerOptions: {css: true},
      }),
    ],
    outfile: 'main.js',
  })
  .then(result => {
    // Check if metafile exists in the result
    if (meta && result.metafile) {
      // Write the metafile object to a JSON file
      fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
      console.log('Build succeeded. Metafile saved to meta.json')
    }
  })
  .catch(() => process.exit(1))
