import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import sveltePlugin from 'esbuild-svelte'
import fs from 'fs'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

async function build() {
  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/closebrackets',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/comment',
      '@codemirror/fold',
      '@codemirror/gutter',
      '@codemirror/highlight',
      '@codemirror/history',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/matchbrackets',
      '@codemirror/panel',
      '@codemirror/rangeset',
      '@codemirror/rectangular-selection',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/stream-parser',
      '@codemirror/text',
      '@codemirror/tooltip',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      ...builtins,
    ],
    format: 'cjs',
    target: 'es2020',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    metafile: prod,
    minify: prod,
    plugins: [
      sveltePlugin({
        compilerOptions: {
          css: 'injected',
          runes: true,
        },
        // filterWarnings: warning =>
        //   !warning.message.toLowerCase().includes('a11y'),
      }),
    ],
    outfile: 'main.js',
  })

  if (!prod) {
    await context.watch()
  }

  if (prod) {
    const result = await context.rebuild()
    if (result.metafile) {
      // Visit https://esbuild.github.io/analyze/ to analyze metafile
      fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
    }
    context.dispose()
  }
}

build().catch(() => process.exit(1))
