# https://taskfile.dev

version: '3'

vars:
  PLUGIN_DIR: C:\PROJECTS\OBSIDIAN\hirn\.obsidian\plugins\obsidian-checklist-plugin

tasks:
  default:
    cmds:
      - npm run build
      - task: copy
  copy: 
    cmds:
      - xcopy main.js "{{.PLUGIN_DIR}}\main.js" /Y


